"""initial

Revision ID: 0001
Revises:
Create Date: 2026-09-20 22:38:10.070073
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_key", sa.String(length=160), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "GOOGLE_TRENDS",
                "WIKIMEDIA",
                "WIKIDATA",
                name="source",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING", "SUCCEEDED", "FAILED", name="runstatus", native_enum=False, length=64
            ),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_key"),
    )
    op.create_index(op.f("ix_collection_runs_source"), "collection_runs", ["source"], unique=False)
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("LIVE", "REPLAY", name="runkind", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING", "SUCCEEDED", "FAILED", name="runstatus", native_enum=False, length=64
            ),
            nullable=False,
        ),
        sa.Column("normalizer_version", sa.String(length=80), nullable=False),
        sa.Column("entity_version", sa.String(length=80), nullable=False),
        sa.Column("classifier_version", sa.String(length=80), nullable=False),
        sa.Column("score_version", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("snapshot_digest", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_runs_as_of"), "pipeline_runs", ["as_of"], unique=False)
    op.create_table(
        "raw_payloads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "GOOGLE_TRENDS",
                "WIKIMEDIA",
                "WIKIDATA",
                name="source",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collector_version", sa.String(length=80), nullable=False),
        sa.Column("parser_version", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "payload_hash", name="uq_raw_source_hash"),
    )
    op.create_index(op.f("ix_raw_payloads_source"), "raw_payloads", ["source"], unique=False)
    op.create_table(
        "trend_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "GOOGLE_TRENDS",
                "WIKIMEDIA",
                "WIKIDATA",
                name="source",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("canonical_text", sa.String(length=500), nullable=False),
        sa.Column("normalized_text", sa.String(length=500), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "ACTIVE",
                "REJECTED",
                "MERGED",
                name="candidatestatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "resolution_status",
            sa.Enum(
                "RESOLVED", "NEEDS_REVIEW", name="resolutionstatus", native_enum=False, length=64
            ),
            nullable=False,
        ),
        sa.Column("normalizer_version", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "normalized_text", name="uq_candidate_source_text"),
    )
    op.create_index(
        "ix_candidate_status_seen", "trend_candidates", ["status", "last_seen_at"], unique=False
    )
    op.create_table(
        "trend_entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("entity_type", sa.String(length=160), nullable=True),
        sa.Column("wikidata_id", sa.String(length=32), nullable=True),
        sa.Column(
            "resolution_status",
            sa.Enum(
                "RESOLVED", "NEEDS_REVIEW", name="resolutionstatus", native_enum=False, length=64
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "SPORTS",
                "ENTERTAINMENT",
                "FOOD",
                "GAME",
                "AI_TECH",
                "MEME_INTERNET",
                "FASHION_BEAUTY",
                "SHOPPING_PRODUCT",
                "OTHER",
                name="category",
                native_enum=False,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column(
            "review_status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "NOISE",
                name="reviewstatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_entity_category_review", "trend_entities", ["category", "review_status"], unique=False
    )
    op.create_index(
        op.f("ix_trend_entities_category"), "trend_entities", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_trend_entities_normalized_name"),
        "trend_entities",
        ["normalized_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trend_entities_wikidata_id"), "trend_entities", ["wikidata_id"], unique=False
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUPPORTED",
                "PARTIALLY_SUPPORTED",
                "UNSUPPORTED",
                "CONTRADICTED",
                name="evidencestatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("publishable", sa.Boolean(), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("evidence_set_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["trend_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_claim_entity_publishable", "claims", ["entity_id", "publishable"], unique=False
    )
    op.create_table(
        "cost_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pipeline_run_id", sa.Integer(), nullable=True),
        sa.Column("cost_type", sa.String(length=80), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("human_minutes", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cost_time_type", "cost_records", ["recorded_at", "cost_type"], unique=False)
    op.create_table(
        "entity_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=500), nullable=False),
        sa.Column("normalized_alias", sa.String(length=500), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["trend_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "normalized_alias", "language", name="uq_entity_alias"),
    )
    op.create_index("ix_alias_normalized", "entity_aliases", ["normalized_alias"], unique=False)
    op.create_table(
        "entity_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("entity_version", sa.String(length=80), nullable=False),
        sa.Column("match_reason", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["trend_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["trend_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "candidate_id", name="uq_entity_candidate"),
    )
    op.create_table(
        "entity_classifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_run_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "SPORTS",
                "ENTERTAINMENT",
                "FOOD",
                "GAME",
                "AI_TECH",
                "MEME_INTERNET",
                "FASHION_BEAUTY",
                "SHOPPING_PRODUCT",
                "OTHER",
                name="category",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("classifier_version", sa.String(length=80), nullable=False),
        sa.Column("classified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["trend_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_classification_entity_time",
        "entity_classifications",
        ["entity_id", "classified_at"],
        unique=False,
    )
    op.create_table(
        "human_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "label",
            sa.Enum(
                "VALID_TREND",
                "TOO_OBVIOUS",
                "NEWS_ONLY",
                "DUPLICATE",
                "WRONG_CATEGORY",
                "BAD_ENTITY_MERGE",
                "NOT_USEFUL",
                "INSUFFICIENT_EVIDENCE",
                name="humanevaluationlabel",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["trend_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_human_eval_entity_time", "human_evaluations", ["entity_id", "created_at"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "APPROVE",
                "REJECT",
                "MERGE",
                "SPLIT",
                "CHANGE_CATEGORY",
                "MARK_NOISE",
                name="reviewaction",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["trend_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_review_entity_time", "reviews", ["entity_id", "created_at"], unique=False)
    op.create_table(
        "source_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("raw_payload_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "GOOGLE_TRENDS",
                "WIKIMEDIA",
                "WIKIDATA",
                name="source",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("source_item_id", sa.String(length=240), nullable=False),
        sa.Column("canonical_text", sa.String(length=500), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["raw_payloads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["collection_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "source_item_id", name="uq_observation_run_item"),
    )
    op.create_index(
        "ix_observation_source_time",
        "source_observations",
        ["source", "source_timestamp"],
        unique=False,
    )
    op.create_table(
        "trend_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_run_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "NEW",
                "RISING",
                "HOT",
                "COOLING",
                name="trendlifecycle",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("breakdown", sa.JSON(), nullable=False),
        sa.Column("missing_inputs", sa.JSON(), nullable=False),
        sa.Column("score_version", sa.String(length=80), nullable=False),
        sa.Column("system_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["trend_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "as_of", "score_version", name="uq_snapshot_version"),
    )
    op.create_index(
        "ix_snapshot_lifecycle_time", "trend_snapshots", ["lifecycle", "as_of"], unique=False
    )
    op.create_table(
        "candidate_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["trend_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["source_observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "observation_id", name="uq_candidate_observation"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "GOOGLE_TRENDS",
                "WIKIMEDIA",
                "WIKIDATA",
                name="source",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("fact", sa.JSON(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["trend_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["source_observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_evidence_entity_time", "evidence", ["entity_id", "observed_at"], unique=False
    )
    op.create_table(
        "claim_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id", "evidence_id", name="uq_claim_evidence"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim_evidence")
    op.drop_index("ix_evidence_entity_time", table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("candidate_observations")
    op.drop_index("ix_snapshot_lifecycle_time", table_name="trend_snapshots")
    op.drop_table("trend_snapshots")
    op.drop_index("ix_observation_source_time", table_name="source_observations")
    op.drop_table("source_observations")
    op.drop_index("ix_review_entity_time", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_human_eval_entity_time", table_name="human_evaluations")
    op.drop_table("human_evaluations")
    op.drop_index("ix_classification_entity_time", table_name="entity_classifications")
    op.drop_table("entity_classifications")
    op.drop_table("entity_candidates")
    op.drop_index("ix_alias_normalized", table_name="entity_aliases")
    op.drop_table("entity_aliases")
    op.drop_index("ix_cost_time_type", table_name="cost_records")
    op.drop_table("cost_records")
    op.drop_index("ix_claim_entity_publishable", table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_trend_entities_wikidata_id"), table_name="trend_entities")
    op.drop_index(op.f("ix_trend_entities_normalized_name"), table_name="trend_entities")
    op.drop_index(op.f("ix_trend_entities_category"), table_name="trend_entities")
    op.drop_index("ix_entity_category_review", table_name="trend_entities")
    op.drop_table("trend_entities")
    op.drop_index("ix_candidate_status_seen", table_name="trend_candidates")
    op.drop_table("trend_candidates")
    op.drop_index(op.f("ix_raw_payloads_source"), table_name="raw_payloads")
    op.drop_table("raw_payloads")
    op.drop_index(op.f("ix_pipeline_runs_as_of"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index(op.f("ix_collection_runs_source"), table_name="collection_runs")
    op.drop_table("collection_runs")
    # ### end Alembic commands ###
