from enum import StrEnum


class Source(StrEnum):
    GOOGLE_TRENDS = "GOOGLE_TRENDS"
    WIKIMEDIA = "WIKIMEDIA"
    WIKIDATA = "WIKIDATA"
    GEEKNEWS = "GEEKNEWS"
    HACKER_NEWS = "HACKER_NEWS"
    GITHUB_RELEASES = "GITHUB_RELEASES"
    OFFICIAL_CLOUDFLARE = "OFFICIAL_CLOUDFLARE"
    OFFICIAL_AWS = "OFFICIAL_AWS"


class SourceType(StrEnum):
    COMMUNITY = "COMMUNITY"
    DEVELOPER = "DEVELOPER"
    OFFICIAL = "OFFICIAL"
    EARLY_SIGNAL = "EARLY_SIGNAL"


class EvidenceKind(StrEnum):
    PRIMARY = "PRIMARY"
    OFFICIAL = "OFFICIAL"
    DEVELOPER = "DEVELOPER"
    COMMUNITY = "COMMUNITY"
    SECONDARY = "SECONDARY"
    EARLY_SIGNAL = "EARLY_SIGNAL"


class ClusterStatus(StrEnum):
    ACTIVE = "ACTIVE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    MERGED = "MERGED"
    REJECTED = "REJECTED"


class EvidenceConfidence(StrEnum):
    REJECTED = "REJECTED"
    LOW = "LOW"
    SUPPORTED = "SUPPORTED"
    STRONG = "STRONG"


class BriefStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    LOW_SIGNAL_DAY = "LOW_SIGNAL_DAY"
    DEGRADED_SOURCE_COVERAGE = "DEGRADED_SOURCE_COVERAGE"
    REJECTED = "REJECTED"


class RunStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class RunKind(StrEnum):
    LIVE = "LIVE"
    REPLAY = "REPLAY"


class CandidateStatus(StrEnum):
    NEW = "NEW"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    MERGED = "MERGED"


class ResolutionStatus(StrEnum):
    RESOLVED = "RESOLVED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class Category(StrEnum):
    SPORTS = "SPORTS"
    ENTERTAINMENT = "ENTERTAINMENT"
    FOOD = "FOOD"
    GAME = "GAME"
    AI_TECH = "AI_TECH"
    MEME_INTERNET = "MEME_INTERNET"
    FASHION_BEAUTY = "FASHION_BEAUTY"
    SHOPPING_PRODUCT = "SHOPPING_PRODUCT"
    OTHER = "OTHER"


class TrendLifecycle(StrEnum):
    NEW = "NEW"
    RISING = "RISING"
    HOT = "HOT"
    COOLING = "COOLING"


class EvidenceStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    CONTRADICTED = "CONTRADICTED"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NOISE = "NOISE"


class ReviewAction(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    MERGE = "MERGE"
    SPLIT = "SPLIT"
    CHANGE_CATEGORY = "CHANGE_CATEGORY"
    MARK_NOISE = "MARK_NOISE"


class HumanEvaluationLabel(StrEnum):
    VALID_TREND = "VALID_TREND"
    TOO_OBVIOUS = "TOO_OBVIOUS"
    NEWS_ONLY = "NEWS_ONLY"
    DUPLICATE = "DUPLICATE"
    WRONG_CATEGORY = "WRONG_CATEGORY"
    BAD_ENTITY_MERGE = "BAD_ENTITY_MERGE"
    NOT_USEFUL = "NOT_USEFUL"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class DataMode(StrEnum):
    LIVE = "LIVE"
    DEMO = "DEMO"
    TEST = "TEST"


class CategoryAvailability(StrEnum):
    ENABLED = "ENABLED"
    EXPERIMENTAL = "EXPERIMENTAL"
    DISABLED = "DISABLED"


class PublicationPolicyMode(StrEnum):
    MANUAL_APPROVAL_REQUIRED = "MANUAL_APPROVAL_REQUIRED"
    AUTO_PUBLISH_ELIGIBLE = "AUTO_PUBLISH_ELIGIBLE"
    AUTO_PUBLISH = "AUTO_PUBLISH"


class FeedbackType(StrEnum):
    NEW_AND_USEFUL = "NEW_AND_USEFUL"
    ALREADY_KNEW = "ALREADY_KNEW"
    NOT_INTERESTED = "NOT_INTERESTED"
    INCORRECT = "INCORRECT"


class NotificationMode(StrEnum):
    OFF = "OFF"
    DAILY_DIGEST = "DAILY_DIGEST"
    IMPORTANT_RISING = "IMPORTANT_RISING"


class ProductEventType(StrEnum):
    ONBOARDING_STARTED = "ONBOARDING_STARTED"
    INTEREST_SELECTED = "INTEREST_SELECTED"
    FEED_VIEWED = "FEED_VIEWED"
    TREND_IMPRESSION = "TREND_IMPRESSION"
    TREND_OPENED = "TREND_OPENED"
    FEEDBACK_NEW_USEFUL = "FEEDBACK_NEW_USEFUL"
    FEEDBACK_ALREADY_KNEW = "FEEDBACK_ALREADY_KNEW"
    FEEDBACK_NOT_INTERESTED = "FEEDBACK_NOT_INTERESTED"
    FEEDBACK_INCORRECT = "FEEDBACK_INCORRECT"
    TREND_SAVED = "TREND_SAVED"
    RETURN_VISIT = "RETURN_VISIT"


class BriefReviewSessionStatus(StrEnum):
    OPEN = "OPEN"
    COMPLETED = "COMPLETED"


class BriefItemUsefulness(StrEnum):
    USEFUL = "USEFUL"
    NOT_USEFUL = "NOT_USEFUL"


class EventSelectionVerdict(StrEnum):
    KEEP = "KEEP"
    SHOULD_EXCLUDE = "SHOULD_EXCLUDE"
    UNSURE = "UNSURE"


class FactCorrectness(StrEnum):
    CORRECT = "CORRECT"
    PARTIALLY_CORRECT = "PARTIALLY_CORRECT"
    INCORRECT = "INCORRECT"
    UNVERIFIABLE = "UNVERIFIABLE"


class InterpretationQuality(StrEnum):
    STRONG = "STRONG"
    ACCEPTABLE = "ACCEPTABLE"
    WEAK = "WEAK"
    MISLEADING = "MISLEADING"


class WatchUsefulness(StrEnum):
    ACTIONABLE = "ACTIONABLE"
    USEFUL = "USEFUL"
    GENERIC = "GENERIC"
    NOT_USEFUL = "NOT_USEFUL"


class VerbosityVerdict(StrEnum):
    TOO_SHORT = "TOO_SHORT"
    JUST_RIGHT = "JUST_RIGHT"
    TOO_LONG = "TOO_LONG"


class EvidenceSetUsefulness(StrEnum):
    ESSENTIAL = "ESSENTIAL"
    HELPFUL = "HELPFUL"
    REDUNDANT = "REDUNDANT"
    NOT_USEFUL = "NOT_USEFUL"


class IncorrectMergeVerdict(StrEnum):
    NO_INCORRECT_MERGE = "NO_INCORRECT_MERGE"
    INCORRECT_MERGE = "INCORRECT_MERGE"
    UNSURE = "UNSURE"


class DuplicateEscapeVerdict(StrEnum):
    NO_DUPLICATE_ESCAPE = "NO_DUPLICATE_ESCAPE"
    DUPLICATE_ESCAPE = "DUPLICATE_ESCAPE"
    UNSURE = "UNSURE"


class MissingEventDiscoverySource(StrEnum):
    GEEKNEWS = "GEEKNEWS"
    HACKER_NEWS = "HACKER_NEWS"
    GITHUB = "GITHUB"
    OFFICIAL_WEB = "OFFICIAL_WEB"
    X = "X"
    ARXIV = "ARXIV"
    HUGGING_FACE = "HUGGING_FACE"
    REDDIT = "REDDIT"
    OTHER = "OTHER"
